# DISCLAIMER: This docker image is only for testings purposes
FROM rust:1.34

# Use nighly build

RUN rustup default nightly

# Add rust formatting tool
RUN rustup component add rustfmt

# Install file watcher
RUN cargo install funzzy
